Task 12
tanchick007/itechart-internship pull request #10
Opened 2021-12-02 10:47 UTC by tanchick007

I also added a new feature: the user can see the quantity of a certain game that  have been added to the cart

https://user-images.githubusercontent.com/77984316/144407233-30f73cc5-90af-4dcd-8148-003d57bded1b.mp4

2021-12-03 12:15 UTC, borodayev requested changes
Generally

2021-12-03 12:15 UTC, borodayev commented on src/server/server.js
> +  }
Лишний раз по массивам лучше не бегать, смотри, можно вот так сделать:

```jsx
app.post("/changepassword", async (req, res) => {
  const { login, password } = req.body;
  const salt = await bcrypt.genSalt(10);
  const newPassHash = await bcrypt.hash(password, salt);
  const user = arrayOfUsers.find((user) => user.login === login);

  const arePasswordsSame = await bcrypt.compare(password, user.password);

  if (arePasswordsSame) {
    res.status(400).send("This is your old password");
  } else {
    user.password = newPassHash;
    res.status(200).send(user);
  }
});
```

2021-12-03 12:15 UTC, borodayev commented on src/server/server.js
> +  const index = arrayOfGames.games.findIndex((game) => game.id === id);
Зачем 2 уровня вложенности? Если база содержит только игры, можно удалить поле "games" в базе и сразу обращаться к ним как `arrayOfGames` (и эту переменную уже назвать как games: 
```jsx 
const games = require("../../public/db.json");
```
)

2021-12-03 12:15 UTC, borodayev commented on src/components/gamesSection/gameBlock.tsx
> +  isAdmin = false,
isAdmin можно получить из стора

2021-12-03 12:15 UTC, borodayev commented on src/components/modals/signIn.tsx
> +          isAdmin: false,
isAdmin c фронта зачем отправлять?

2021-12-03 12:15 UTC, borodayev commented on src/components/modals/signUp.tsx
> +          isAdmin: false,
same

2021-12-03 12:15 UTC, borodayev commented on src/server/server.js
> +const arrayOfUsers = [
Но лучше их тоже вынести в users.json как игры сейчас

2021-12-03 12:53 UTC, borodayev commented
@tanchick007 если найдешь время/силы/желание можешь ознакомиться с этими материалами (скорее всего потом в работе будешь с ними сталкиваться):
- [Одно из мощных решений для менеджмента форм в реакте](https://github.com/final-form/react-final-form)
- [JWT авторизация](https://www.youtube.com/watch?v=vQldMjSJ6-w&list=PL_7AF7b1iBet7MUJzeci0lknE3XtwXbZ2&index=4&ab_channel=JavaScript.Ninja), конечно больше для бэкендеров, но принцип работы понимать все же стоит.
- Почитай про принципы SOLID, в частности про 'S' - single responsibility и 'I' - interface segregation. Остальные на фронте встречаются редко. Есть много докладов/книжек на эту тему ([пример](https://www.youtube.com/watch?v=wi3wPzReKZQ&ab_channel=BadooTech))
- Композиция vs наследование. Частый вопрос на собесах по реакту.

2021-12-03 13:19 UTC, tanchick007 commented on src/components/searchbar/searchbar.tsx
> +
Раньше, если юзер переходил с одной категории на другую, в searchbar оставалось прошлое значение(прикрепляю видео ниже, чтобы было более понятно о чем речь):
https://user-images.githubusercontent.com/77984316/144608722-be34fd26-0069-406e-8302-42b95f6b7be0.mp4
Теперь же, при переходе на другую категорию searchbar очищается:
https://user-images.githubusercontent.com/77984316/144608897-a20b95b8-1fd1-4f51-8eb4-1f6629e8bb33.mp4

2021-12-03 13:22 UTC, tanchick007 commented on src/components/pages/home.tsx
> +  const [isHidden, setIsHidden] = useState<boolean>(false);
В случае, если у нас в `searchbar` пусто, идет скрытие секции Search results
https://user-images.githubusercontent.com/77984316/144609468-4c1c3062-43d2-49d3-97c8-3f5bee0c2e41.mp4

2021-12-03 13:29 UTC, tanchick007 commented
> 

Спасибо большое, обязательно ознакомлюсь со всем вышеперечисленным как раз на выходных😄

2021-12-03 13:32 UTC, tanchick007 commented on src/components/modals/signIn.tsx
> +          isAdmin: false,
Если не указать `isAdmin` в req.body, vs код ругается
![why is admin](https://user-images.githubusercontent.com/77984316/144610761-5f78762c-2f9b-48d4-b359-ecc7bb142938.png)

2021-12-03 18:22 UTC, borodayev commented on src/components/pages/home.tsx
> +  const [isHidden, setIsHidden] = useState<boolean>(false);
Тогда лучше переименовать isHiddenSearchResults

2021-12-03 18:43 UTC, borodayev commented on src/components/modals/signIn.tsx
> +          isAdmin: false,
vscode не всегда адекватен) Это axios имеет какие-то странные типы, по дефолту входные и выходные данные реквеста должны быть одного типа. Если посмотреть типизацию метода post внутри axios:
![Screen Shot 2021-12-04 at 00 39 19](https://user-images.githubusercontent.com/19319629/144655676-7e62572f-61ad-4d8a-8583-08f71b2b5bba.png)

То можно увидеть что есть возможность передать разные типы для входных и выходных данных. Получится что-то вроде этого:

```jsx
 type User = {
    login: string;
    username: string;
    password: string;
  };

  function handleChange(e: { preventDefault: () => void }) {
    const { isLoginValid } = validate({
      login: userCredentials.login,
    });
    e.preventDefault();
    if (isLoginValid) {
      axios
        .post<User, AxiosResponse<User & { isAdmin: boolean }>>("http://localhost:3001/signin", {
          login: userCredentials.login,
          password: userCredentials.password,
          username: "",
        })
        .then((response) => {
          if (response.status === 200) {
            const { login, username, password, isAdmin } = response.data;
            if (onSignin) {
              onSignin(login, username, password, isAdmin);
            }
            if (location.state !== null && location.state !== undefined) {
              history.push(location.state.from);
            } else {
              history.push("/");
            }
            toggleModal();
          }
        })
        .catch((err) => {
          console.error(err);
          setErrors((prevState) => ({ ...prevState, hasSignUpError: true, errorText: err.response.data }));
        });
    } else {
      setErrors((prevState) => ({ ...prevState, hasLoginError: !isLoginValid }));
    }
  }
```

2021-12-03 19:19 UTC, borodayev requested changes
Добавил несколько комментов + не все прошлые треды были зарезолвлены, перепроверь пожалуйста и помечай как зарезолвленные после фиксов.

2021-12-03 19:19 UTC, borodayev commented on src/components/gamesSection/gameBlock.tsx
>    id,
Есть еще один способ задать дефолтные пропсы:

```jsx
const GameBlock = (props: Game): JSX.Element => {
  const {
    id = 0,
    image = "defaultValue",
    name,
    price,
    rating,
    description,
    ageLimit,
    genre,
    platform,
    isAdmin = false,
  } = props;
```

плюс если много пропсов прилетает, лучше потратить одну строчку и экстрактить их из объекта props, так получается более читабельно

2021-12-03 19:19 UTC, borodayev commented on src/components/pages/products.tsx
> +  }, [window.location.search, genre, age, criteria, type, isUpdated]);
Имелось ввиду что когда читаешь isUpdated или hasChanged непонятно к чему относится эта переменная и изменение какой сущности она отражает. Плюс вокруг много разных переменных с разными контекстами (файл products.tsx и возможно он необязательно содержит логику с играми, фильтры и так далее). Поэтому приходится искать декларацию переменной на 25 строке и смотреть что в нее записывается. Лучше придумать что-то вроде hasGamesChanged/hasProductsChanged/hasGamesTouched, etc...

2021-12-03 19:19 UTC, borodayev commented on src/components/searchbar/searchbar.tsx
> +const DefaultProps = {
А это уже не тип, а обычная переменная, поэтому с маленькой буквы. И вообще попробуй при экстракции пропсов задавать дефолты как я писал выше, возможно так будет лучше)

2021-12-03 19:19 UTC, borodayev commented on src/server/server.js
> +  let games = arrayOfGames;
Не, я имел ввиду везде переименовать, либо можешь оставить `arrayOfGames`. Просто перезаписывать одинаковое значение в другую переменную в данном контексте не имеет смысла.

2021-12-06 08:03 UTC, tanchick007 commented on src/components/searchbar/searchbar.tsx
> +const DefaultProps = {
Способ экстракции пропсов, который ты описал выше, и правда лучше выглядит, но вот почему-то в `searchbar` он отказывается их принимать как дефолтные в таком виде(
Я оставлю `defaultProps` как переменную, но в дальнейшем если что буду использовать метод, который ты писал выше)
![Screenshot_1](https://user-images.githubusercontent.com/77984316/144809039-24ec7af8-7bef-4023-a625-be1a1f9a1f07.png)

2021-12-06 08:23 UTC, borodayev commented on src/components/searchbar/searchbar.tsx
> +const DefaultProps = {
Без проблем)

2021-12-06 15:51 UTC, borodayev approved these changes

2021-12-07 08:21 UTC, merged