Task 8
tanchick007/itechart-internship pull request #7
Opened 2021-11-15 08:57 UTC by tanchick007

2021-11-16 08:27 UTC, borodayev commented
@tanchick007 there is a white gap on the profile page:

![image](https://user-images.githubusercontent.com/19319629/141948497-1da8d859-9d9a-42df-8c0a-13ba0873f96e.png)

2021-11-16 08:49 UTC, borodayev requested changes
Left several comments, please ask questions if u'll have some.

2021-11-16 08:49 UTC, borodayev commented on src/helpers/validationErrors.ts
> +  bad_login: "Invalid login",
Usually, these keys are uppercased like `BAD_LOGIN`.

2021-11-16 08:49 UTC, borodayev commented on src/server/server.js
> +  for (let i = 0; i < arrayOfUsers.length; i++) {
Use [Array.find()](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

2021-11-16 08:49 UTC, borodayev commented on src/server/server.js
> +  for (let i = 0; i < arrayOfUsers.length; i++) {
Also, refactor other endpoints, I saw a similar approach there.

2021-11-16 08:49 UTC, borodayev commented on src/components/pages/profilePage.tsx
> +      .get(`http://localhost:3001/getprofile/${userCredentials.userName}`)
What `userName`means? Seems that it contains similar info as `login` does:
![image](https://user-images.githubusercontent.com/19319629/141949136-0cd4e06f-4adf-4038-9c96-f30f59d614ec.png)

Is there any sense to add additional variable then?

2021-11-16 08:49 UTC, borodayev commented on src/components/pages/profilePage.tsx
> +    description: "",
`description` and `userImage` are not user credentials, right?

2021-11-16 08:49 UTC, borodayev commented on src/components/pages/profilePage.tsx
> +  const updateFile = (e: ChangeEvent<HTMLInputElement>) => {
That's saving images only on the browser, if u wanna introduce images, let's save them properly on the server, or remove it at all.

2021-11-16 08:49 UTC, borodayev commented on src/server/server.js
> +      userImage: "/images/img.jpg",
The default image is not working, since there is no such file by this path. We can discuss how to implement this later.

2021-11-16 08:49 UTC, borodayev commented on src/server/server.js
> +});
This is not readable, needs to be refactored. Let's separate `login` and `userName` fields. They should be different. That would simplify the logic. Users should be found only by `login`.

2021-11-16 08:49 UTC, borodayev commented on src/server/server.js
> +  const user = arrayOfUsers.filter((item) => item.login === login);
[].filter() gives an array as a result so the variable should be named as `users`. Better use [].find().

2021-11-16 08:59 UTC, borodayev commented
@tanchick007 there are also issues on UI like modals don't close after clicking outside. After logging out the auth modal is showing up right away. While logging in, if the password is incorrect, the error message is wrong. 
Please take a look:
https://www.loom.com/share/d9b9c04c3f974e49bf141f6721867c7e

2021-11-23 07:31 UTC, borodayev requested changes
Left minor comments, once resolved pls merge, nice job!

2021-11-23 07:31 UTC, borodayev commented on src/server/server.js
> +    res.status(400).send("This login is already taken");
If I'm not wrong, `res.send()` doesn't stop execution of the code. So, you need either wrap your code with `else`:

```jsx
if (sameLogin) {
....
} else {
....
}
```

Or put `return`:

```jsx
if (sameLogin) {
  return res.status(400).send("This login is already taken");
}
```

Please re-check docs of express

2021-11-23 07:31 UTC, borodayev commented on src/server/server.js
> +    res.status(400).send("This user doesn't exist");
Same here

2021-11-23 07:31 UTC, borodayev commented on src/server/server.js
>      }
Для чего эта проверка? `username` не может быть одинаковым? Получается если 2 юзера с одинаковым именем, и у них разные логины то изменить `username` нельзя?

2021-11-23 08:49 UTC, tanchick007 commented on src/server/server.js
>      }
Да, идея была в том, что у каждого юзера уникальный `login` и уникальный `username`, но я сейчас нашла баг, когда эту логику с уникальным`username`мом можно обойти при регистрации, поэтому я уберу этот блок, и теперь будет допускаться, что у разных юзеров может быть одинаковый `username`.

2021-11-23 08:56 UTC, merged