Task 11
tanchick007/itechart-internship pull request #9
Opened 2021-11-26 13:38 UTC by tanchick007

2021-11-29 08:23 UTC, borodayev requested changes
Left several comments, pls refactor

2021-11-29 08:23 UTC, borodayev commented on src/components/gamesSection/gameBlock.tsx
> +} & typeof defaultProps;
Для чего typeof defaultProps?

2021-11-29 08:23 UTC, borodayev commented on src/components/gamesSection/gameBlock.tsx
> +  const handleGame = () => {
addToCart?

2021-11-29 08:58 UTC, tanchick007 commented on src/components/pages/home.tsx
> +  };
Я почему-то сразу не догадалась перенести этот хэндлер на уровень ниже, поэтому когда я использовала spread оператор, у меня вс код ругался. Сейчас я перенесла хэндлер и теперь вс код больше не ругается)
![Screenshot_2](https://user-images.githubusercontent.com/77984316/143837455-4bca62ec-f465-4d01-b7d0-f816f102e4a2.png)

2021-11-29 09:03 UTC, borodayev commented on src/components/pages/home.tsx
> +  };
В таком случае нужно просто порядок пропсов поменять. Тогда сначала спред попадет в пропсы, а потом все последующие переменные перезапишут пропсы из спреда если у них одинаковые ключи

```jsx
<GameBlock key={item.id} {...item} onAddGame={onAddGame} />
```

2021-11-30 09:16 UTC, borodayev approved these changes
👍

2021-11-30 09:31 UTC, merged